name: jrbeutler
favicon: null
layout_spectrum: 0.8947882070206106
typography_spectrum: 0.8054037203546613
title: Leadership Thoughts I find interesting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a8a9ad'
    - '#f7921c'
    - '#231f20'
    - '#747476'
  brandStrength: 0.4171207291074097
  lightness: 0.7916440588887781
  saturation: 0.4062211043201387
  rhythmicContrast: 0.3550665301736444
purpose: []
